[AutoRun]
enabled=false
program=

[BitTorrent]
Session\DefaultSavePath=/downloads/
Session\Port=6881
Session\QueueingSystemEnabled=true
Session\SSL\Port=7958
Session\TempPath=/downloads/incomplete/

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=8

[Network]
PortForwardingEnabled=false

[Preferences]
Connection\PortRangeMin=6881
Connection\UPnP=false
Downloads\SavePath=/downloads/
Downloads\TempPath=/downloads/incomplete/
WebUI\Address=*
WebUI\Password_PBKDF2="@ByteArray(hwgiaDyBklHMhzynIeNWjQ==:Tu74Ya75hzkdMzQcbYYrbAa3jI0=)"
WebUI\Port=8081
WebUI\ServerDomains=*